install: gradle wrapper --gradle-version 4.4

language: java
jdk:
  - openjdk8

# 어느 브래친가 푸시될 떄 수행할지 지정
branch:
  only:
    - master

before_install:
  - chmod +x gradlew

# Travis CI 서버의 Home
# 그레이들을 통해 의존성을 받게 되면 이를 해당 디렉토리에 캐시하여, 같은의존성은 다음 배포떄부터 다시 받지 않도록 설정
cache :
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# master 브랜치에 푸시 되었을때 수행하는 명령어
script: "./gradlew clean build"

# deploy 명령어가 실행되기 전에 수행함.
# CodeDeploy가 Jar를 인식하지 못하므로 zip으로 압축
before_deploy:
  - mkdir -p before-deploy
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy *
  - cd ../ && mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/springboot-study.zip

# S3로 파일 업로드 혹은 CodeDeploy로 배포 등 외부서비소와 연동될 행위를 선언
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: spring.hjh.build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: spring.hjh.build
    key: springboot-study.zip
    bundle_type: zip
    application: springboot-study
    deployment_group: springboot-study
    region: ap-northeast-2
    wait-until-deployed: true

# 자동알람
notifications:
  email:
    recipients:
      - gmacto123@gmail.com
