language: java
jdk:
  - openjdk8

# 어느 브래친가 푸시될 떄 수행할지 지정
branch:
  only:
    - master


# Travis CI 서버의 Home
# 그레이들을 통해 의존성을 받게 되면 이를 해당 디렉토리에 캐시하여, 같은의존성은 다음 배포떄부터 다시 받지 않도록 설정
cache :
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# master 브랜치에 푸시 되었을때 수행하는 명령어
script: "./gradlew clean build"

# 자동알람
notifications:
  email:
    recipients:
      - gmacto123@gmail.com
